# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [labeled]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'develop' && github.event.label.name == 'chromatic'
    # if: github.event_name == 'pull_request' && github.base_ref == 'develop' && contains(github.event.pull_request.labels.*.name, 'chromatic')
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: echo ${{ github.event.label.name}}
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        run: echo 'publish to chromatic'