# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        run: echo 'publish to chromatic'