# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Eslint"]
    branches:
      - "develop"
    types:
      - completed
    # pull_request:
    #   branches:
    #     - 'develop'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        run: echo 'publish to chromatic'
