name: "Publish nightly Package to npmjs cron task"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  nightly:
    uses: ./.github/workflows/nightly.yml
    with:
      ref: 'develop'
    secrets: inherit
