name: "Publish nightly Package to npmjs cron task"

on:
  schedule:
    - cron: '0/10 * * * *'
  workflow_dispatch:
      secrets:
            NPM_TOKEN:
                description: 'Npm Token'
                required: false

jobs:
  nightly:
    uses: ./.github/workflows/nightly.yml
    secrets:
      TEST_SECRET: ${{secrets.TEST_SECRET}}
