name: "Publish nightly Package to npmjs cron task"

on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  nightly:
    uses: ./.github/workflows/nightly.yml
    secrets:
      TEST_SECRET: ${secrets.TEST_SECRET}
