# .github/workflows/chromatic.yml

# Workflow name
name: "EsLint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "variables"
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.ref_name}}
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "next_version=$(cat package.json | jq -r '.version')-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      
      - name: "variables 2"
        run: |
          echo "Sha: ${{ env.sha_short }}"
          echo "Shanext: ${{ env.next_version }}"
          echo "npm_version=$(npm view react@next version)" >> "$GITHUB_ENV"
      - name: Check publish status
        id: check
        uses: tehpsalmist/npm-publish-status-action@v1
      - name: "variables 3"
        run: |
          echo "${{ env.sho_short }} - ${{ env.npm_version }}"
          echo "${{ steps.check.outputs.exists }}"
        
      #- name: Update package.json version
       # uses: jossef/action-set-json-field@v2.1
       # with:
       #   file: package.json
       #   field: version
       #   value: ${{ env.sha_short }}
   # 
    #  - name: Commit files
    #    run: |
    #      git config --local user.email "action@github.com"
    #      git config --local user.name "GitHub Action"
    #      git add -A
    #      git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
    #      git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        
    #  - name: Push changes
    #    uses: ad-m/github-push-action@v0.6.0
    #    with:
    #      github_token: ${{ github.token }}
      - name: run eslint
        run: yarn && yarn lint
