# .github/workflows/chromatic.yml

# Workflow name
name: "EsLint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "variables"
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.ref_name}}
          echo $(git rev-parse --short "$GITHUB_SHA")
      - name: run eslint
        run: yarn && yarn lint
