# .github/workflows/nightly.yml

# Workflow name
name: "Publish nightly Package to npmjs"

on:
    workflow_call:
        secrets:
            TEST_SECRET:
                description: 'Npm Token'
                required: false
    workflow_dispatch:
        secrets:
            TEST_SECRET:
                description: 'Npm Token'
                required: false


jobs:
  prepublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: get next version
        id: version
        run: |
          git checkout develop
          echo "secret"
          echo ${{ secrets.TEST_SECRET }}
  
        
