# .github/workflows/chromatic.yml

# Workflow name
name: "Storybook"

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' || github.ref_name == 'main'
    steps:
      - name: get archive name
        run: |
          [[ github.ref_name = 'develop' ]] && a='storybook-dev' || a='storybook-main' }}
          echo "archive_name=$a" >> $GITHUB_OUTPUT
      - name: print variables
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.ref_name}}
          echo ${{ inputs.name }}
          echo ${{ steps.vars.outputs.archive_name }}
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: publish storybook main
        run: echo 'publish storybook main'