# Workflow name
name: Publish dev storybook

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Eslint"]
    branches:
      - "develop"
    types:
      - completed

jobs:
  storybook-develop:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: build-storybook
        run: echo 'storybook develop!!'
