# .github/workflows/chromatic.yml

# Workflow name
name: "Storybook"

on:
  workflow_dispatch:
  workflow_call:
    # inputs:
    #   name:
    #     required: true
    #     type: string

env:
  name: ${{ github.ref_name == 'develop' && 'storybook-dev' || 'storybook-main' }}

jobs:
  publish:
    name: publish ${{ env.name }}
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' || github.ref_name == 'main'
    steps:
      - name: print variables
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.ref_name}}
          echo ${{ inputs.name }}
          echo ${{ env.name }}
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: publish storybook
        run: echo 'publish storybook'
