on:
  push:
    tags:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: GitHub Tag Name example
       run: |
         echo "$(pwd)"
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         NPM_VERSION=$(npm show aristid-ds version) >> $GITHUB_OUTPUT
         echo "Package version $LATEST"
         PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"') >> $GITHUB_OUTPUT
         echo "package.json version $PACKAGE_VERSION"
     - name: check equality
       if: ${{ steps.vars.outputs.NPM_VERSION }} == ${{ steps.vars.outputs.PACKAGE_VERSION }}
       run : echo "versions match !!"
