on:
  push:
    tags:
      - '*'
jobs:
  github-example-tags:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: build
       run: yarn && yarn build-storybook
     - name: upload artifact
       uses: actions/upload-artifact@v3
         with:
           name: storybook
           path: ./storybook-static
     - name: GitHub Tag Name example
       run: |
         echo "$(pwd)"
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         NPM_VERSION=$(npm show aristid-ds version)
         echo "NPM_VERSION=$NPM_VERSION" >> $GITHUB_ENV
         echo "Package version $LATEST"
         PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
         echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
         echo "package.json version $PACKAGE_VERSION"
     - name: print values
       run: |
         echo "${{ env.NPM_VERSION }}"
         echo "${{ env.PACKAGE_VERSION }}"
     - name: check equality
       if: ${{ env.NPM_VERSION }} != ${{ env.PACKAGE_VERSION }}
       run : echo "versions mismatch !!"
