name: publish

on:
  push:
    branches:
      - 'develop'
    tags:
      - '*'

jobs:
  prepare-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name}} == "tags"
    steps:
      - uses: actions/checkout@v2
      - uses: nowsprinting/check-version-format-action@v3
        id: version
      - uses: geritol/match-tag-to-package-version@0.2.0
        id: match-version
        if: steps.version.outputs.is_valid == true
  publish-npm:
    runs-on: ubuntu-latest
    needs: prepare-publish
    steps:
      - uses: actions/checkout@v2
      - name: build-package
        run: yarn && yarn build
      # - name: publish npm # only for final package
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.x'
      #     registry-url: 'https://registry.npmjs.org'
      # - run: yarn ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  storybook-main:
    runs-on: ubuntu-latest
    needs: prepare-publish
    steps:
      - uses: actions/checkoout@v2
      - name: build-storybook
        run: yarn && yarn build-storybook
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-main
          path: ./storybook-static
  storybook-develop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == "push"
    steps:
      - uses: actions/checkoout@v2
        with:
          ref: 'develop'
      - name: build-storybook
        run: yarn && yarn build-storybook
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-develop
          path: ./storybook-static
