name: "Test"

# Event for the workflow
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - run: echo "kikoo"
