name: "Test"

# Event for the workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'

jobs:
  chromatic-deployment:
    if: github.event_name == 'workflow_dispatch'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - run: echo "kikoo"
      - run: echo "${{ github.event_name }}"
