# .github/workflows/workflow.yml

# Workflow name
name: "Workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'develop'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: print variables
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.ref_name}}
          echo ${{ github.ref}}
          echo ${{ github}}
      - name: test
        if: startsWith(github.ref, 'refs/tag')
        run: echo 'youhou'
  eslint:
    uses: ./.github/workflows/eslint.yml
  chromatic:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop' && contains(github.event.pull_request.labels.*.name, 'chromatic')
    needs: eslint
    uses: ./.github/workflows/chromatic.yml
  # storybook:
  #   if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop')
  #   needs: eslint
  #   uses: ./.github/workflows/storybook.yml
    # with:
    #   name: 'stprybook-main'
  # storybook-dev:
  #   if: github.event_name == 'push' && github.ref_name == 'develop'
  #   needs: eslint
  #   uses: ./.github/workflows/storybook.yml
  #   with:
  #     name: 'storybook-develop'