# .github/workflows/workflow.yml

# Workflow name
name: "Workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'develop'

jobs:
  eslint:
    uses: ./.github/workflows/eslint.yml
  chromatic:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    needs: eslint
    uses: ./.github/workflows/chromatic.yml
  storybook:
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop')
    needs: eslint
    uses: ./.github/workflows/storybook.yml
    # with:
    #   name: 'stprybook-main'
  # storybook-dev:
  #   if: github.event_name == 'push' && github.ref_name == 'develop'
  #   needs: eslint
  #   uses: ./.github/workflows/storybook.yml
  #   with:
  #     name: 'storybook-develop'